### ISSUE TITLE
DB Modules

### ISSUE THREAD

**Issue by eslachance** [UnseenFaith/komada#13]
Database modules for various types of databases: 
- JSON (flatfile)
- SQLite
- LocalStorage
- pgsql
- mysql
- etc

Each module would need to have specific functions, to be compatible: 
- Init function (create db/tables, temp files, etc)
- Config (DB config especially, user/pass, etc)
- Table management (add, remove, reset, etc)
- Row management (add, remove, reset, update, etc)
- unload

**Comment by eslachance** [comment]
Partially complete: still requires `unload` feature, as well as more examples (localstorage is done)
See 3fb351ddaacd7c6e45004b52bf2472515ed1cee1

**Comment by CyberiumShadow** [comment]
@eslachance Is this still active?
