### ISSUE TITLE
Message Processors

### ISSUE THREAD

**Issue by eslachance** [UnseenFaith/komada#14]
Special message processors that are executed upon each message. Few examples:
- Profanity Filter
- Levels (think Mee6 levels, ugh)
- Spam Detection
- Blacklists
- etc

The processor should be a single function, and should return "false" if it's deemed that the command handler should stop processing (aka commands should not be executed). For instance the Blacklist would return false if an ID is blacklisted and should be ignored.

**Comment by bdistin** [comment]
Slight modification of this idea, using Promises.all() fail-fast behavior to determine if the command handler should stop processing.

Actually, now that I am reading this again, it seems like there are 2 ideas here kinda mashed up. Levels/Spam Detection (No mention?)/Profanity would act on every message, not just commands in which case their success/use should have no bearing on the command handler.

However things like, disable/permission levels/blacklists/ect would. Which is what my commit is set up for.

**Comment by eslachance** [comment]
Added to Command Inhibitors, in PR #16
