### ISSUE TITLE
v0.18 ready event not firing

### ISSUE THREAD

**Issue by PDStig** [UnseenFaith/komada#150]
### Version of Komada
0.18 on Centos 7

### Are core files modified?
No

### Describe the problem
I noticed however that after upgrading to 0.18, ready.js in the events folder is not executing on bot being ready.

### Expected Behaviour
When the bot loads, ready.js from events is fired. I have a console.log to tell me when it is fired. It also creates an open port to receive metadata from a radio system to put as a channel topic in a guild.

### Actual Behaviour
ready.js does not appear to fire. Nothing in the log about it firing, and the server port supposed to start up on ready is not started.

### Steps to Reproduce.
1. create a ready.js script in events.
2. Make ready.js output something to the console on fire.
3. Start the bot via. pm2 or via. node.
4. ready.js does not appear to fire.

**Comment by CyberiumShadow** [comment]
This is a known bug and is currently fixed on the Utils branch.

I'll backport the fix onto 0.18 and as such, 0.18.1 will be the fixed version.

I'll get back to you once its done.

**Comment by CyberiumShadow** [comment]
Ready for merge to Indev and incidentally master as well for a NPM release as 0.18.1 as per #143 

Just waiting for @UnseenFaith to approve the PR

**Comment by UnseenFaith** [comment]
@Lovinity Fixed and will be instated on the next NPM version of Komada, (0.18.1, UtilsHotFix).
Thank you for using the issues tab for reporting this bug.
