### ISSUE TITLE
[CRITICAL] help command not working

### ISSUE THREAD

**Issue by kyranet** [UnseenFaith/komada#161]
### Version of Komada
0.18.5#indev

### Are core files modified?
No, happens to Komada Bot too.

### Describe the problem
When you execute the help command, unless you're the owner of the bot, it doesn't work.
Error `STATUS 400: Bad request: Cannot send an empty message`. It happens ONLY when GuildMember.permLevel (using Utils/Extendables) is 0, or DMs the command help as user.permLevel = 0.

### Expected Behaviour
Send the commands to DMs.

### Actual Behaviour
Notifies the user that the commands have been send to DMs, however, it doesn't send any message, just print "Bad Request" on console (with depth null).

### Steps to Reproduce.
Install komada Indev v0.18.5, execute the help command being member.permLevel == 0 (works with higher permLevel).

**Comment by UnseenFaith** [comment]
Fixed in latest Indev.
