### ISSUE TITLE
Issue with command loader

### ISSUE THREAD

**Issue by szymex73** [UnseenFaith/komada#167]
### Version of Komada
0.18.1

### Are core files modified?
No

### Describe the problem
I wrote basic function that should send a message and then edit it

### Expected Behaviour
The command file should load just fine

### Actual Behaviour
At startup the loader ejects some errors about \n in markdown (???) that look like this:
```
{ code: null,
  message: 'Could not load new command data: /`/`/`js\n/home/szymex/test/discord/komada.js/commands/Misc/test.js:2\n  const message = await msg.channel.sendMessage("Ping?").catch(err => client.funcs.log(err, "error"))\n                        ^^^\nSyntaxError: Unexpected identifier\n    at createScript (vm.js:53:10)\n    at Object.runInThisContext (vm.js:95:10)\n    at Module._compile (module.js:543:28)\n    at Object.Module._extensions..js (module.js:580:10)\n    at Module.load (module.js:488:32)\n    at tryModuleLoad (module.js:447:12)\n    at Function.Module._load (module.js:439:3)\n    at require (internal/module.js:20:19)\n    at Promise (/home/szymex/node_modules/komada/functions/loadSingleCommand.js:30:13)\n    at Object.module.exports [as loadSingleCommand] (/home/szymex/node_modules/komada/functions/loadSingleCommand.js:3:72)\n    at files.forEach (/home/szymex/node_modules/komada/utils/loadCommands.js:10:26)\n    at Array.forEach (native)\n    at Promise (/home/szymex/node_modules/komada/utils/loadCommands.js:9:11)\n    at process._tickCallback (internal/process/next_tick.js:109:7)/`/`/`',
  stack: null }
```
I've put the backslashes in the error msg so it wouldn't collide with GH's markdown

### Steps to Reproduce.
I don't know, my PC is Linux Mint 18.1 Cinnamon
Node 7.7.2
This is my main file: [Link to gist](https://gist.github.com/szymex73/c71225f7110c205bdaca93ed477a88de)
And my ./commands/Misc/test.js file: [Link to gist](https://gist.github.com/szymex73/9110604af950243dca39f7f76f3f293b)

**Comment by FOG-Yamato** [comment]
You missed calling the async function in your test.js command file, that why it couldn't load the async/await functionality.

**Comment by UnseenFaith** [comment]
What Yamato said is correct, or you forgot to run Komada with the harmony flag (if needed).

To run async inside a komada command you need to do
`exports.run = async (client, msg, ...args) => {
// code here
}`

Or you need to run your bot with the harmony flag
`node --harmony myfile.js`
