### ISSUE TITLE
Can't use space into conf command

### ISSUE THREAD

**Issue by p4rkrs** [UnseenFaith/komada#171]
### Version of Komada
v0.18.10

### Are core files modified?
Nope

### Describe the problem

When I do set the conf to a message with space example: Welcome to the server

That's will set only Welcome..
### Expected Behaviour

Will set Welcome to the server
### Actual Behaviour

Set only Welcome
### Steps to Reproduce.
Create an string into the conf file, and try to set it with space

Same for the adminRole and modRole

**Comment by UnseenFaith** [comment]
Will be fixed in the next version of Komada
