### ISSUE TITLE
Reload command crashes when not given a parameter

### ISSUE THREAD

**Issue by FOG-Yamato** [UnseenFaith/komada#19]
> D:\c2857\Desktop\Discord Bots\guidebot\cmds\reload.js:11
>     if (params[0].includes(".js")) params[0] = params[0].replace(".js","");
>                  ^
> 
> TypeError: Cannot read property 'includes' of undefined
>     at Object.exports.run (D:\c2857\Desktop\Discord Bots\guidebot\cmds\reload.js:11:18)
>     at Client.bot.on.msg (D:\c2857\Desktop\Discord Bots\guidebot\app.js:77:9)
>     at emitOne (events.js:96:13)
>     at Client.emit (events.js:188:7)
>     at MessageCreateHandler.handle (D:\c2857\Desktop\Discord Bots\guidebot\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
>     at WebSocketPacketManager.handle (D:\c2857\Desktop\Discord Bots\guidebot\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:94:65)
>     at WebSocketManager.eventMessage (D:\c2857\Desktop\Discord Bots\guidebot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:220:31)
>     at WebSocket.ws.onmessage (D:\c2857\Desktop\Discord Bots\guidebot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:78:37)
>     at WebSocket.onMessage (D:\c2857\Desktop\Discord Bots\guidebot\node_modules\ws\lib\WebSocket.js:442:14)
>     at emitTwo (events.js:106:13)

I myself fixed it by adding a return if params[0] is null

**Comment by eslachance** [comment]
Fixed in #16
