### ISSUE TITLE
addKey parameter check bug

### ISSUE THREAD

**Issue by PDStig** [UnseenFaith/komada#195]
### Version of Komada
0.18.1

### Are core files modified?
No

### Describe the problem
The addKey function incorrectly checks for values in key and defaultValue.

### Expected Behaviour
The if condition checking for key and DefaultValue checks for an unset variable.

### Actual Behaviour
The if condition checks for false instead. This results in problems if you need to use false as DefaultValue.

### Steps to Reproduce.
!eval client.funcs.confs.addKey("cmdPrompt", false)

**Comment by UnseenFaith** [comment]
That's a known issue and has been fixed (or should have been fixed on our latest project). There's no plans to backport this to 0.18.1, so you can expect it to be fixed in the next Minor update. Until then, I will leave this issue open though. For now, a workaround can be setting it true and then toggling it.

**Comment by PDStig** [comment]
This bug was not fixed in 0.19.0

https://gyazo.com/6c794e86bf4bece9135407aea23bb5bc

**Comment by CyberiumShadow** [comment]
Welp...

**Comment by PDStig** [comment]
It's okay. Happens to me sometimes too when I think I patched a bug and really didn't :P

**Comment by CyberiumShadow** [comment]
No changes to the config code was made in 0.19.0

Your best choice is either continue the workaround given by @UnseenFaith or attempt to use indev which **is breaking if the readme is not read.**

**Comment by PDStig** [comment]
Neither would be an option for profanityFilter... otherwise the bot will by default start filtering a bunch of stuff given the code. :P . So I will postpone development of the profanity filter until bug is fixed.

**Comment by UnseenFaith** [comment]
@Lovinity Ah, that was fixed on the current Indev and wasn't backported to 0.19.0. However, I'm currently in the process of rewriting the JSON configuration system again, and I will also be updated the confs command to be able to edit everything in the configuration, as opposed to having to eval something. So you can expect that in 0.20.0 most likely.

**Comment by CyberiumShadow** [comment]
This is no longer relevant due to a new config system being put into place for 0.20.x

As of now, there are no plans to backport a config fix to 0.19.x
