### ISSUE TITLE
permissionLevel.js not correctly working

### ISSUE THREAD

**Issue by PDStig** [UnseenFaith/komada#221]
### Version of Komada
0.19.0

### Are core files modified?
Only a couple, but nothing that interferes with permissionLevel.js

### Describe the problem
permissionLevel.js returns the wrong number for permissions.

### Expected Behaviour
permissionLevel.js returns 10 for bot owner, 4 for guild owner, 3 for adminRole user, 2 for modRole user, 0 for everyone else.

### Actual Behaviour
permissionLevel.js ignores admins, mods, and guild owners; only returns 10 for bot owner or 0 for everyone else.

### Steps to Reproduce.
Using a command which accesses msg.author.permLevel.

**Comment by kyranet** [comment]
permissionLevel is something nuked in this version. It's now structured as the following: https://github.com/dirigeants/komada/blob/indev/client.js#L127-L191

To have your custom permStructure, open app.js (or whatever your main file is called), and inside the object `Komada`, add `permStructure: [{}, {}, ... {}]` as shown in the main file I have just linked.

It **MUST** have 11 objects, from 0 to 10.

To check if a user has enough permissions, use `msg.hasAtleastPermissionLevel(2)`

**Comment by CyberiumShadow** [comment]
@kyranet You're referencing indev which is 0.20.0

**Comment by CyberiumShadow** [comment]
@Lovinity Can i get a few screenshots?

**Comment by kyranet** [comment]
Thing is, msg.author.permLevel gives you either 0 or 10 (if you are the bot's owner). However, it doesn't have access to roles nor guild. 

You should use msg.member.permLevel instead. 👍
