### ISSUE TITLE
Feature: Requiring Functions Inside Functions

### ISSUE THREAD

**Issue by Skillz4Killz** [UnseenFaith/komada#333]
### Version of Komada
github:dirigeants/komada#indev

### Are core files modified?
No

### Describe the problem
It isn't really a problem but would be an awesome feature to add on. Right now i have about 5 function files. I am in need of creating a new function file but this new function will require calling one of those previous 5 functions. However, if the new function loads before the older functions then it wont work at all. It would be nice to have a way to require functions similar to how in commands exports.conf you can require certain functions.

### Expected Behaviour
A function that requires other functions don't load before other functions.

**Comment by kyranet** [comment]
To start with, there is literally **no way** to load all pieces at the same, nor we are loading them in an specific order, we load all the pieces with a [Promise.all](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise/all), and how are you using these functions? I have worked with whole nets of functions but never got that issue.

**Comment by Skillz4Killz** [comment]
I don't think they should load at the same time just in a specific order. What I am hoping for is if you could force load a function before loading another function.

1) This is a complete function that converts a number into a letter.
2) This is a new function that requires the previous function to take the letter and give back a word based on that letter.

Currently, I was trying to do something similar but it kept erroring out. I believe it was because function 2 was loaded before function 1 meaning function 2 was never able to call function 1.

As suggested on the discord I changed the name of function 2 to be alphabetically after function 1 and it worked. 

This is a solution but it would be nice to be able to make sure a function loads before another function without having to destroy the function file names.

**Comment by FOG-Yamato** [comment]
1st of all that option is based on how Promise.all works
2nd of all what you're doing is really bad because you'll run into problems with loading and reloading

**Comment by bdistin** [comment]
Promise.all doesn't completely make everything happen at the same time. Certain async actions are passed to other thread workers. In this case file system calls. Say you have a very big file and a very small file, theoretically with a promise all, you could completely load the small file before the big file's thread workers resolve. In any other sequential system you would have the sum of all loading times. Where as a Promise.all would take advantage of any free thread time which can result in loading times less than the sum of all loading times.

Besides that, what you are asking for goes against a core design principle of komada/klasa. Komada translates into pieces. And each piece should be independent of each other. I personally imagine them as legos, where each piece is independent, but at the same time snaps together and works to build anything you want.

As FOG-Yamato says, you will run into problems loading and reloading them. Which is true, but it also poses the possibility of circular requires. A requires B, B requires C, C requires A. In what order would that be loaded in?

Finally I make a suggestion. There are two ways of logically fixing your problem:
1. Neither piece calls each other unexplicitly. Rather they call each other explicitly, after everything is loaded.
2. One piece is turned into a child module of the other piece. Use module.exports and require to require the child module like you would any other dependency.

**Comment by Skillz4Killz** [comment]
Thank you, everyone bdistin just gave me the perfect explanation and solution to my problem.
