### ISSUE TITLE
Suggestion: Adding a Space To The Beginning of Help

### ISSUE THREAD

**Issue by Skillz4Killz** [UnseenFaith/komada#338]
### Version of Komada
github:dirigeants/komada#indev

### Are core files modified?
No, not until I added a space to fix this issue.

### Describe the problem
The color highlighting on the help messages that arrive in the DM can be affected by the prefix. For example by using the `.` prefix it changes the entire color to Blue instead of the awesome Blue and Orange. Changing the prefix to `,` or `/` solves this issue but that forces users to use a specific prefix. I would suggest adding a space to the help.

**Problem:** https://cdn.discordapp.com/attachments/339948384368721921/348868699165556746/unknown.png

**Suggestion:** https://cdn.discordapp.com/attachments/342436526380154881/348924110941847553/unknown.png

### Steps to Reproduce.
Set prefix to `.` and type .help

**Comment by CyberiumShadow** [comment]
Can confirm lol 
![image](https://user-images.githubusercontent.com/4259904/29499603-c853392e-8658-11e7-88d2-c8101c615518.png)

**Comment by CyberiumShadow** [comment]
This is mainly just a quirk with highlight.js
I'll obtain the opinion of other devs first

**Comment by pedall** [comment]
Imo not so good since you can’t copy paste anymore with a space
