### ISSUE TITLE
BUG: Commandlogger Finalizer Doesn't Work

### ISSUE THREAD

**Issue by Skillz4Killz** [UnseenFaith/komada#340]
### Version of Komada
Latest Komada#master

### Are core files modified?
Only the help command to add a ` ${prefix}` space in the beginning so the asiidoc colors work and dont get ruined by the prefix.

### Describe the problem
CommandLogger doesnt log any commands when enabled in the config.json file.

### Expected Behaviour
Log the commands as described in docs.

### Actual Behaviour
None

### Steps to Reproduce.
Edit json file to have it enabled -> use a command

```
"cmdLogging": true,
```

**Comment by UnseenFaith** [comment]
Are you enabling it in the actual Komada Configuration? It won't do you any good if you're not telling Komada that you want to use it.

**Comment by Skillz4Killz** [comment]
this was solved, error in my config.json but might want to edit the docs to show `cmdLogging: false` in the bot configuration
