### ISSUE TITLE
BUG: SettingGateway#updateArray() is not type-agnostic

### ISSUE THREAD

**Issue by mcumbers** [UnseenFaith/komada#345]
### Version of Komada
0.20.8

### Are core files modified?
No

### Describe the problem
It's not possible to use the updateArray function with SettingGateway instances initialized with a type other than guild

### Expected Behaviour
updateArray should update arrays in SettingGateway instances based on all types

### Actual Behaviour
updateArray throws an error and fails to update arrays on SettingGateway instances other than ones based on guild types

### Steps to Reproduce.
- Create a new SettingGateway instance based on other type (eg: User) with an array key in the schema
- Create an entry with an object of your SettingGateway instance type
- Use updateArray to try to modify the array key

**Comment by kyranet** [comment]
Found the [issue](https://github.com/dirigeants/komada/blob/master/src/classes/settingGateway.js#L224-L225). Unlike SettingGateway#update, SettingGateway#updateArray does not have a parameter reserved for guild resolving.

**Comment by UnseenFaith** [comment]
Should be fixed in #335 @mcumbers 

Let me know if it's not.
