### ISSUE TITLE
Command usage not being reloaded with reload command

### ISSUE THREAD

**Issue by ghost** [UnseenFaith/komada#346]
### Version of Komada
v0.20.7

### Are core files modified?
No.

### Describe the problem
Reloading a command doesn't reload the commands'  usage arguments, if you had wrote it incorrectly and tried to reload it to fix it - or at least not in this case.

### Expected Behaviour
Reloading the command which previously had incorrect syntax in the usage arguments, then fixed, should update the command usage and reload it without errors.

### Actual Behaviour
The same error is displayed when trying to reload the command, as was displayed when you made the syntax mistake, despite the usage being fixed. A reboot is necessary to reload the command properly.

### Steps to Reproduce.
1. Upload this [test.js](https://gist.github.com/Magnaboy/68759e527bcb3c96f5c9cd50442f90d1) (a simple command with some usage args) command and load it, the arguments are written correctly.
2. Edit the file on your server and change the first argument from `<anInteger:int{1,10000}>` to `<anInteger:int{1,10000>` and reload the command, you will get an error because it is incorrect.
3. Edit the file and fix the syntax error by putting the `}` back in, and try to reload the command, it will show the same error in Step 2.

**Comment by UnseenFaith** [comment]
In the process of fixing this now, just trying to find a appropriate way of doing it.

**Comment by UnseenFaith** [comment]
Should be fixed (for all pieces) in #347 / 0.20.9
