### ISSUE TITLE
SettingsGateway guild settings get reset to defaults or null

### ISSUE THREAD

**Issue by asmahood** [UnseenFaith/komada#357]
### Version of Komada
0.20.10

### Are core files modified?
No

### Describe the problem
I only notice when I get errors with my moderation commands, however, my Guild settings are being reset back to their defaults or null. I do not know when this happens.

### Expected Behaviour
Guild settings wouldn't get randomly reset?

### Actual Behaviour
I set the guild settings, then a few days later I eval my guild settings and they are reset back to null

### Steps to Reproduce.
Using eval to add items to the guild settings, such as a modLog channel ID or adminRole ID

Proof: On September 8th
https://gyazo.com/7ea7ecc815324e4873bda3ff899fb18b

On September 11th
https://gyazo.com/90d9ddb48f08ce364dd4d503c482c689

I haven't manually reset them.

**Comment by UnseenFaith** [comment]
Already a known issue and the bug has been patched, there's just no PR for it yet.

**Comment by CyberiumShadow** [comment]
Fixed in #356
