### ISSUE TITLE
Help Command not working

### ISSUE THREAD

**Issue by ecinteza** [UnseenFaith/komada#381]
### Version of Komada
0.21.1

### Are core files modified?
Nope

### Describe the problem
When I try the help command it says
"":x: | You have DMs disabled, I couldn't send you the commands in DMs."
but if i try eval message.author.send(`something`) is working
and is working to send messages to the bot too
I have like 45 commands + System commands

### Expected Behaviour
To be sending me all the commands

### Actual Behaviour
It sends me nothing

### Steps to Reproduce.
I used help
didn't work
i used eval message.author.send(`something`)
worked
i messaged the bot
worked
i used help again
didn't work

**Comment by UnseenFaith** [comment]
Due to the nature of the command (and how old it is really..) it's probably due to another error. You can confirm this by transfering the help command and console.log()'ing the error that's being returned.

**Comment by ecinteza** [comment]
![image](https://user-images.githubusercontent.com/24627356/36154629-b6bef5a6-10da-11e8-9832-1436489f5905.png)
I changed a bit the command and it says in DM that i have DMs disabled

**Comment by UnseenFaith** [comment]
You still didn't do what i said though. You need to log the actual error that's being thrown.. obviously it's not that you have DMs disabled..

Change the .catch() to log the exception instead of saying "You have DM's disabled"

**Comment by ecinteza** [comment]
<img width="960" alt="error" src="https://user-images.githubusercontent.com/24627356/36155440-0cf68400-10dd-11e8-96c0-5eacb2001690.png">
This is the error i got

**Comment by UnseenFaith** [comment]
Apparently your message is too long to send. You'll have to edit the formatting of the command or split more.

**Comment by ecinteza** [comment]
aaaand how do i do that? (im new in programming ;-;)

**Comment by SuperOP535** [comment]
categories

**Comment by ecinteza** [comment]
Now is working, i made 2 help messages and sends me every command (idk how to do it in other ways xd)
```js
  const helpMessage = [];
  const helpMessage2 = [];
  for (let cat = 0; cat < categories.length/2; cat++) {
    helpMessage.push(`**${categories[cat]} Commands**: \`\`\`asciidoc`);
    const subCategories = Object.keys(help[categories[cat]]);
    for (let subCat = 0; subCat < subCategories.length; subCat++) helpMessage.push(`= ${subCategories[subCat]} =`, `${help[categories[cat]][subCategories[subCat]].join("\n")}\n`);
    helpMessage.push("```\n\u200b");
  }
  for (let cat = categories.length/2; cat < categories.length; cat++) {
    helpMessage2.push(`**${categories[cat]} Commands**: \`\`\`asciidoc`);
    const subCategories = Object.keys(help[categories[cat]]);
    for (let subCat = 0; subCat < subCategories.length; subCat++) helpMessage2.push(`= ${subCategories[subCat]} =`, `${help[categories[cat]][subCategories[subCat]].join("\n")}\n`);
    helpMessage2.push("```\n\u200b");
  }
  return msg.author.send(helpMessage, { split: { char: "\u200b" } })
    .then (() => { msg.author.send(helpMessage2, {split: { char: "\u200b"}})})```
